"""Add telegram_chat_id to invites

Revision ID: 2b33fb1aed4c
Revises: 17ab8692f539
Create Date: 2026-07-24 22:36:40.979552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b33fb1aed4c'
down_revision: Union[str, Sequence[str], None] = '17ab8692f539'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invites', sa.Column('telegram_chat_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_invites_telegram_chat_id'), 'invites', ['telegram_chat_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invites_telegram_chat_id'), table_name='invites')
    op.drop_column('invites', 'telegram_chat_id')
    # ### end Alembic commands ###
