"""create papers and chunks tables

Revision ID: 45030a76a766
Revises: 
Create Date: 2026-07-07 14:05:06.124795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45030a76a766'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('papers',
    sa.Column('arxiv_id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('abstract', sa.Text(), nullable=False),
    sa.Column('authors', sa.JSON(), nullable=False),
    sa.Column('categories', sa.JSON(), nullable=False),
    sa.Column('primary_category', sa.String(length=32), nullable=False),
    sa.Column('published_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pdf_url', sa.String(length=512), nullable=False),
    sa.Column('doi', sa.String(length=128), nullable=True),
    sa.Column('ingestion_status', sa.Enum('pending', 'fetched', 'chunked', 'embedded', 'indexed', 'failed', name='ingestionstatus'), nullable=False),
    sa.Column('ingestion_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('arxiv_id')
    )
    op.create_table('chunks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('paper_id', sa.String(length=32), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('opensearch_doc_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.arxiv_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chunks_paper_id'), 'chunks', ['paper_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chunks_paper_id'), table_name='chunks')
    op.drop_table('chunks')
    op.drop_table('papers')
    # ### end Alembic commands ###
