"""Add invites table and invite_token to query_logs

Revision ID: dc22e2b91c3b
Revises: f338740ef09f
Create Date: 2026-07-23 23:22:56.804646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc22e2b91c3b'
down_revision: Union[str, Sequence[str], None] = 'f338740ef09f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
