"""Add invites table and invite_token to query_logs

Revision ID: f338740ef09f
Revises: e8ef52efada3
Create Date: 2026-07-23 18:25:30.182596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f338740ef09f'
down_revision: Union[str, Sequence[str], None] = 'e8ef52efada3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invites',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('daily_question_limit', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('first_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invites_token'), 'invites', ['token'], unique=True)
    op.add_column('query_logs', sa.Column('invite_token', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_query_logs_invite_token'), 'query_logs', ['invite_token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_query_logs_invite_token'), table_name='query_logs')
    op.drop_column('query_logs', 'invite_token')
    op.drop_index(op.f('ix_invites_token'), table_name='invites')
    op.drop_table('invites')
    # ### end Alembic commands ###
